spring.datasource.url=${JADE_DATASOURCE_URL}
spring.datasource.username=${JADE_DATASOURCE_USERNAME}
spring.datasource.password=${JADE_DATASOURCE_PASSWORD}

logging.level.co.kr.ghlee.jade.api.jadehr=${JADEHR_LOG_LEVEL:INFO}
logging.level.co.kr.ghlee.jade.common.api=${JADE_COMMON_LOG_LEVEL:INFO}
